example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "H2"
spring.datasource.platform:  "h2"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.h2.Driver"
spring.datasource.url: "jdbc:h2:tcp://localhost/~/eagle_eye_dev"
spring.datasource.username: "thoughtmechanix"
spring.datasource.password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.H2Dialect"
spring.jpa.properties.hibernate.hbm2ddl.auto: "update"