#spring:
#  cloud:
#    stream:
#      bindings:
#        output:
#            destination:  orgChangeTopic
#            content-type: application/json
#      kafka:
#        binder:
#          zkNodes: localhost
#          brokers: localhost

spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

#security:
# oauth2:
#  resource:
#   userInfoUri: http://localhost:8901/auth/user